using Gitster.Core.Models;

namespace Gitster.Core.Common;

/// <summary>
/// Derives a human-readable name for a stash from its raw git message and changed files.
/// Pure, side-effect-free — can be unit-tested without any repo access.
/// </summary>
public static class StashNamer
{
    /// <summary>
    /// Returns a display name for a stash.
    /// If the message is user-supplied (not git's auto "WIP on …" / "On …"),
    /// the message is returned verbatim. Otherwise the name is derived from the
    /// changed-file list using the algorithm described in the Phase 2b plan.
    /// </summary>
    public static string Generate(string rawMessage, string branchName, IReadOnlyList<StashFileChange> files)
    {
        if (!IsAutoGeneratedMessage(rawMessage))
            return rawMessage.Trim();

        if (files.Count == 0)
            return string.IsNullOrEmpty(branchName) ? "stash" : $"wip on {branchName}";

        var added   = files.Count(f => f.Kind == StashChangeKind.Added);
        var deleted = files.Count(f => f.Kind == StashChangeKind.Deleted);
        var verb    = added > deleted * 2 ? "add"
                    : deleted > added * 2 ? "remove"
                    : "wip";

        // Sort by change size descending; take up to 3 filenames
        var sorted    = files.OrderByDescending(f => f.Added + f.Removed).ToList();
        var topNames  = sorted.Take(3).Select(f => System.IO.Path.GetFileName(f.Path)).ToList();
        var extra     = files.Count - topNames.Count;

        // Most common top-level directory
        var topDir = files
            .Select(f =>
            {
                var slash = f.Path.IndexOfAny(['/', '\\']);
                return slash > 0 ? f.Path[..slash] : null;
            })
            .Where(d => d != null)
            .GroupBy(d => d)
            .OrderByDescending(g => g.Count())
            .Select(g => g.Key)
            .FirstOrDefault();

        var fileNames = string.Join(", ", topNames);
        if (extra > 0) fileNames += $", +{extra}";

        if (!string.IsNullOrEmpty(topDir) && files.Count > 1)
            return $"{verb}: {files.Count} files in {topDir} · {fileNames}";

        if (files.Count > 3)
            return $"{verb}: {files.Count} files";

        return $"{verb}: {fileNames}";
    }

    /// <summary>
    /// Extracts the branch name from git's auto-generated stash message.
    /// E.g. "WIP on master: abc1234 Msg" → "master".
    /// Returns an empty string if parsing fails.
    /// </summary>
    public static string ParseBranchFromMessage(string rawMessage)
    {
        var match = System.Text.RegularExpressions.Regex.Match(
            rawMessage,
            @"^(?:WIP on|On)\s+([^:]+):",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);
        return match.Success ? match.Groups[1].Value.Trim() : string.Empty;
    }

    private static bool IsAutoGeneratedMessage(string msg)
        => string.IsNullOrWhiteSpace(msg)
        || msg.StartsWith("WIP on ", StringComparison.OrdinalIgnoreCase)
        || msg.StartsWith("On ", StringComparison.OrdinalIgnoreCase);
}
